Initial Setup with config management.
RealDevSquad/website-learn-backend pull request #3
Opened 2023-03-28 07:07 UTC by RitikJaiswal75

This is a PR for the initial setup of a GO Lang backend.
- included viper for multiple config management
- add cors 
- create a health endpoint

2023-03-29 12:38 UTC, prakashchoudhary07 requested changes

2023-03-29 12:38 UTC, prakashchoudhary07 commented on src/routes/routesHandler.go
> +	router.GET("/health/dashboard", handlers.Dashboard)
Why do you need a dashboard here?
What does it return?

2023-03-29 12:38 UTC, prakashchoudhary07 commented on src/main.go
> +
Why are you reading it from args here?
Lets use ENV's here

2023-03-29 12:38 UTC, prakashchoudhary07 commented on src/handlers/dashboard.go
> +}
What is this doing? why do we need this?

2023-03-31 08:42 UTC, RitikJaiswal75 commented on src/main.go
> +
With reference to our communication over discord, I used this.
Link to the discord communication: https://discord.com/channels/673083527624916993/781622799868493864/1089968784904831040

2023-03-31 08:44 UTC, RitikJaiswal75 commented on src/routes/routesHandler.go
> +	router.GET("/health/dashboard", handlers.Dashboard)
That is going to be an authenticated route. Also, I followed your PR reference where a monitor was set up
https://github.com/Real-Dev-Squad/gopher-cloud-service/pull/1/files#diff-20c10829adccb91d328e30581c58a0db895a36fa08653253978ea310755114deR20

2023-03-31 08:45 UTC, RitikJaiswal75 commented on src/handlers/dashboard.go
> +}
It has become an authenticated route

2023-07-20 05:21 UTC, closed without merging